# Generated by Django 3.1 on 2020-08-27 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0003_currentsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='level',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='select_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sheet.level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='select_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sheet.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
