# Generated by Django 3.1 on 2020-08-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0004_auto_20200827_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentsheet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.AlterField(
            model_name='index',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='CurrentSheet',
        ),
    ]
