# Generated by Django 3.1 on 2020-09-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0005_auto_20200830_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='level',
            new_name='sheet_name',
        ),
        migrations.RemoveField(
            model_name='index',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='index',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='index',
            name='topic',
        ),
        migrations.AlterField(
            model_name='questions',
            name='correct_option',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
