# Generated by Django 3.1 on 2020-09-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0006_auto_20200903_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='user',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='index',
            name='sheet_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
