# Generated by Django 3.1 on 2020-09-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0008_auto_20200904_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet_name',
            name='advanced_user',
        ),
        migrations.RemoveField(
            model_name='sheet_name',
            name='basic_user',
        ),
        migrations.RemoveField(
            model_name='sheet_name',
            name='foundation_user',
        ),
        migrations.AddField(
            model_name='sheet_name',
            name='user_level',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
