# Generated by Django 3.1 on 2020-09-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0010_auto_20200905_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet_name',
            name='advanced_user',
        ),
        migrations.RemoveField(
            model_name='sheet_name',
            name='basic_user',
        ),
        migrations.RemoveField(
            model_name='sheet_name',
            name='foundation_user',
        ),
    ]
