# Generated by Django 3.1 on 2020-09-06 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0011_auto_20200905_0703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='hintimage',
            new_name='hint_image',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='questionimage',
            new_name='question_image',
        ),
        migrations.RenameField(
            model_name='sheet_name',
            old_name='image',
            new_name='concept_image',
        ),
    ]
