# Generated by Django 3.1 on 2020-09-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0014_auto_20200906_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='hint_image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sheet_name',
            name='concept_image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
