# Generated by Django 3.1 on 2020-09-06 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0015_auto_20200906_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='select_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sheet.level'),
            preserve_default=False,
        ),
    ]
