# Generated by Django 3.1 on 2020-09-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0016_auto_20200906_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['select_level']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['select_level']},
        ),
    ]
