# Generated by Django 3.1 on 2020-09-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0017_auto_20200907_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('sheet_name', models.CharField(max_length=50)),
                ('question_no', models.PositiveSmallIntegerField()),
                ('user_answer', models.CharField(max_length=50)),
                ('correct_answer', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['question_no'],
            },
        ),
    ]
