# Generated by Django 3.1 on 2020-09-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0018_useranswers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='correct_option',
            new_name='correct_answer',
        ),
    ]
