# Generated by Django 3.1 on 2020-09-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0020_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet_name',
            name='allow_calc',
            field=models.BooleanField(default=False),
        ),
    ]
