# Generated by Django 3.1 on 2020-09-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='advanced',
        ),
        migrations.RemoveField(
            model_name='level',
            name='basic',
        ),
        migrations.RemoveField(
            model_name='level',
            name='foundation',
        ),
        migrations.AddField(
            model_name='level',
            name='level',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='level',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
