# Generated by Django 3.1 on 2020-09-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200905_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='level',
        ),
        migrations.AddField(
            model_name='level',
            name='advanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='level',
            name='basic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='level',
            name='foundation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
