# Generated by Django 3.1 on 2020-08-21 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userresult', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['score'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50)),
                ('question_no', models.PositiveSmallIntegerField()),
                ('question_id', models.CharField(max_length=50)),
                ('user_answer', models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=15)),
                ('user_answer_blank', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useranswers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['question_no'],
            },
        ),
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.PositiveSmallIntegerField(unique=True)),
                ('test_name', models.CharField(max_length=50, unique=True)),
                ('test_type', models.CharField(choices=[('weekly', 'weekly'), ('mock', 'mock'), ('subject', 'subject'), ('topic', 'topic')], max_length=20)),
                ('level', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('time_limit_in_minutes', models.PositiveSmallIntegerField()),
                ('no_of_questions', models.PositiveSmallIntegerField()),
                ('positive_marks', models.IntegerField(blank=True)),
                ('negative_marks', models.IntegerField(blank=True)),
                ('description', models.CharField(blank=True, max_length=70)),
                ('published', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='testpaper.exam')),
                ('select_level', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sheet.level')),
                ('select_subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sheet.subject')),
                ('select_topic', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sheet.topic')),
            ],
            options={
                'verbose_name_plural': 'TestPapers',
                'ordering': ['test_number'],
            },
        ),
        migrations.CreateModel(
            name='TestIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('select_test_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpaper.testpaper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testindex', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50)),
                ('question_no', models.PositiveSmallIntegerField()),
                ('question', models.CharField(max_length=500)),
                ('questionimage', models.ImageField(blank=True, upload_to='')),
                ('blank_type', models.BooleanField(default=False)),
                ('option_a', models.CharField(blank=True, max_length=100)),
                ('option_b', models.CharField(blank=True, max_length=100)),
                ('option_c', models.CharField(blank=True, max_length=100)),
                ('option_d', models.CharField(blank=True, max_length=100)),
                ('correct_option', models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=15)),
                ('answer_blank', models.CharField(blank=True, max_length=100, null=True)),
                ('solution', models.CharField(blank=True, max_length=500)),
                ('solution_image', models.ImageField(blank=True, upload_to='')),
                ('solution_video', models.URLField(blank=True)),
                ('select_test_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpaper.testpaper')),
            ],
            options={
                'ordering': ['question_no'],
            },
        ),
    ]
