# Generated by Django 3.1 on 2020-08-30 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='select_exam',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='testpaper.exam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='exam',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='test_type',
            field=models.CharField(choices=[('weekly', 'weekly'), ('mock', 'mock'), ('subject', 'subject'), ('topic', 'topic'), ('topic', 'topic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='question_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
