# Generated by Django 3.1 on 2020-08-30 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0004_auto_20200827_1534'),
        ('testpaper', '0002_auto_20200830_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpaper',
            name='select_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheet.subject'),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='select_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheet.topic'),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='test_type',
            field=models.CharField(choices=[('weekly', 'weekly'), ('mock', 'mock'), ('subject', 'subject'), ('topic', 'topic'), ('previous_year_paper', 'previous_year_paper')], max_length=20),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='topic',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
