# Generated by Django 3.1 on 2020-08-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0003_auto_20200830_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswers',
            name='question_id',
        ),
        migrations.AddField(
            model_name='useranswers',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useranswers',
            name='correct_answer_blank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='user_answer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
