# Generated by Django 3.1 on 2020-08-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0005_auto_20200830_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testindex',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
