# Generated by Django 3.1 on 2020-08-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0006_auto_20200830_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswers',
            name='user',
        ),
        migrations.AddField(
            model_name='useranswers',
            name='user_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='correct_answer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='question_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='user_answer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
