# Generated by Django 3.1 on 2020-08-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0008_auto_20200830_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_no',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='question_no',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
