# Generated by Django 3.1 on 2020-09-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0009_auto_20200830_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswers',
            name='marks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
