# Generated by Django 3.1 on 2020-09-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0011_auto_20200902_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='correct_option',
            new_name='correct_answer',
        ),
    ]
