# Generated by Django 3.1 on 2020-09-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0012_auto_20200902_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
