# Generated by Django 3.1 on 2020-09-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0013_userresult_submitted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresult',
            old_name='user',
            new_name='user_name',
        ),
    ]
