# Generated by Django 3.1 on 2020-09-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0014_auto_20200902_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresult',
            name='test_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
