# Generated by Django 3.1 on 2020-09-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0015_auto_20200902_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='advanced_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='basic_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='foundation_user',
            field=models.BooleanField(default=False),
        ),
    ]
