# Generated by Django 3.1 on 2020-09-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0016_auto_20200904_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpaper',
            name='advanced_user',
        ),
        migrations.RemoveField(
            model_name='testpaper',
            name='basic_user',
        ),
        migrations.RemoveField(
            model_name='testpaper',
            name='foundation_user',
        ),
    ]
