# Generated by Django 3.1 on 2020-09-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0017_auto_20200905_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='questionimage',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='solution_image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
