# Generated by Django 3.1 on 2020-09-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0018_auto_20200906_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='questionimage',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='solution_image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
