# Generated by Django 3.1 on 2020-09-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0019_auto_20200906_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresult',
            name='test_name',
            field=models.CharField(max_length=100),
        ),
    ]
