# Generated by Django 3.1 on 2020-09-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0022_auto_20200913_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flag',
            old_name='test_ame',
            new_name='test_name',
        ),
    ]
