# Generated by Django 3.1 on 2020-09-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0024_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='allow_calc',
            field=models.BooleanField(default=False),
        ),
    ]
